# api/routes/files.py — File upload/download endpoints
#
# KEY LESSON: Always use _ensure_dir() with PermissionError handling.
# A raw os.makedirs() crash on unwritable paths produces a 500 traceback
# instead of a clean error response.

import os
import shutil
from fastapi import APIRouter, Depends, UploadFile, File, HTTPException
from fastapi.responses import FileResponse

from api.core.config import load_config
from api.auth.token_auth import verify_token

router = APIRouter()
config = load_config()


def _ensure_dir(path: str) -> None:
    """Create directory if it doesn't exist, raise HTTP 500 if we can't."""
    try:
        os.makedirs(path, exist_ok=True)
    except PermissionError:
        raise HTTPException(
            status_code=500,
            detail=f"Server cannot create directory: {path}. "
                   f"Check filesystem permissions.",
        )


@router.post("/files/in")
async def upload_file(
    file: UploadFile = File(...),
    _: bool = Depends(verify_token),
):
    """Upload a file for Hermes to process."""
    upload_dir = config["files"]["upload_dir"]
    _ensure_dir(upload_dir)

    file_path = os.path.join(upload_dir, file.filename)

    try:
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
    except PermissionError:
        raise HTTPException(
            status_code=500,
            detail=f"Cannot write to upload directory: {upload_dir}",
        )

    return {
        "filename": file.filename,
        "path": file_path,
        "size_bytes": os.path.getsize(file_path),
        "message": f"File uploaded. Reference in prompt: {file_path}",
    }


@router.get("/files/out/{filename}")
async def download_file(filename: str, _: bool = Depends(verify_token)):
    """Download a file generated by Hermes."""
    output_dir = config["files"]["output_dir"]
    file_path = os.path.join(output_dir, filename)

    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(file_path, filename=filename)


@router.get("/files/out")
async def list_output_files(_: bool = Depends(verify_token)):
    """List all files in the output directory."""
    output_dir = config["files"]["output_dir"]
    if not os.path.exists(output_dir):
        return {"files": []}

    files = []
    for f in os.listdir(output_dir):
        path = os.path.join(output_dir, f)
        if os.path.isfile(path):
            files.append({
                "filename": f,
                "size_bytes": os.path.getsize(path),
                "path": path,
            })
    return {"files": files}
