# templates/hermes_client.py — Python Client Library
#
# Usage from any Python app (ChainLit, Flask, scripts):
#
#   from hermes_client import HermesClient
#   client = HermesClient("http://192.168.1.100:8000", token="your-token")
#
#   r1 = client.chat("Perform brainstorming for a new product")
#   r2 = client.chat("Narrow to top 3", session_id=r1["session_id"])

import requests
from typing import Optional


class HermesClient:
    """Stateful Hermes Agent client."""

    def __init__(self, base_url: str, token: str = None):
        self.base_url = base_url.rstrip("/")
        self.headers = {}
        if token:
            self.headers["Authorization"] = f"Bearer {token}"

    def chat(
        self,
        prompt: str,
        session_id: Optional[str] = None,
        skills: Optional[list[str]] = None,
        max_turns: Optional[int] = None,
        timeout: Optional[int] = 300,
    ) -> dict:
        """Send a chat message to Hermes."""
        payload = {"prompt": prompt}
        if session_id:
            payload["session_id"] = session_id
        if skills:
            payload["skills"] = skills
        if max_turns:
            payload["max_turns"] = max_turns

        resp = requests.post(
            f"{self.base_url}/chat",
            json=payload,
            headers=self.headers,
            timeout=timeout,
        )
        resp.raise_for_status()
        return resp.json()

    def upload_file(self, file_path: str) -> dict:
        """Upload a file for Hermes to process."""
        with open(file_path, "rb") as f:
            resp = requests.post(
                f"{self.base_url}/files/in",
                files={"file": f},
                headers=self.headers,
                timeout=120,
            )
        resp.raise_for_status()
        return resp.json()

    def download_file(self, filename: str, save_path: str) -> str:
        """Download a file generated by Hermes."""
        resp = requests.get(
            f"{self.base_url}/files/out/{filename}",
            headers=self.headers,
            stream=True,
            timeout=120,
        )
        resp.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=8192):
                f.write(chunk)
        return save_path

    def list_files(self) -> dict:
        resp = requests.get(f"{self.base_url}/files/out",
                           headers=self.headers, timeout=10)
        resp.raise_for_status()
        return resp.json()

    def health(self) -> dict:
        return requests.get(f"{self.base_url}/health", timeout=10).json()

    def list_sessions(self) -> dict:
        resp = requests.get(f"{self.base_url}/sessions",
                           headers=self.headers, timeout=10)
        resp.raise_for_status()
        return resp.json()
