#!/usr/bin/env python3
"""
generate_release_notes_pdf.py

Dynamic CLI tool to render structured release notes and enhancement tables into
a professionally styled landscape PDF document using ReportLab.

Accepts either:
  1. A Markdown file (.md) with tables and headers
  2. A JSON file (.json) with structured sections and items

Usage:
    uv run --with reportlab python generate_release_notes_pdf.py --input <notes.md|data.json> --output <output.pdf> [--title <title>]
"""

import sys
import os
import re
import json
import argparse
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas that performs a two-pass render to dynamically calculate total pages."""
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Header (on pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 580, "Release Notes — Enhancements & New Capabilities Reference")
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(36, 574, 756, 574)
            
        # Footer
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(756, 25, footer_text)
        self.drawString(36, 25, "Release Notes Analysis | Generated by Antigravity Agent")
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(36, 35, 756, 35)
        self.restoreState()

def parse_markdown_tables(md_text):
    """Parses a markdown string containing headers and markdown tables into structured dict."""
    lines = md_text.splitlines()
    data = {
        "title": "Release Notes: New Capabilities & Enhancements",
        "subtitle": "Categorized breakdown of features, simplified explanations, examples, and use cases.",
        "sections": []
    }
    
    current_section = None
    in_table = False
    table_lines = []
    
    for line in lines:
        stripped = line.strip()
        
        # Extract title from first # heading
        if stripped.startswith("# ") and not current_section:
            data["title"] = stripped[2:].strip()
            continue
            
        # Extract section from ## or ### heading
        if stripped.startswith("## ") or stripped.startswith("### "):
            # Flush previous table if any
            if current_section and table_lines:
                parse_table_block(current_section, table_lines)
                table_lines = []
            
            heading_text = stripped.lstrip("#").strip()
            if not heading_text.lower().startswith("summary matrix"):
                current_section = {"title": heading_text, "items": []}
                data["sections"].append(current_section)
            else:
                current_section = None
            continue
            
        # Detect table rows
        if stripped.startswith("|") and stripped.endswith("|"):
            if current_section:
                table_lines.append(stripped)
        else:
            if current_section and table_lines:
                parse_table_block(current_section, table_lines)
                table_lines = []

    if current_section and table_lines:
        parse_table_block(current_section, table_lines)

    return data

def parse_table_block(section_dict, table_lines):
    """Parses raw markdown table lines and appends items to section_dict."""
    if len(table_lines) < 3:
        return
    
    # Line 0: Header
    # Line 1: Separator |---|---|
    # Line 2+: Data rows
    for row_line in table_lines[2:]:
        cells = [c.strip() for c in row_line.strip("|").split("|")]
        if len(cells) >= 4:
            # Clean bold/code markers for clean rendering
            cap = cells[0].strip()
            exp = cells[1].strip()
            ex = cells[2].strip()
            uc = cells[3].strip()
            
            section_dict["items"].append({
                "capability": cap,
                "explanation": exp,
                "example": ex,
                "use_case": uc
            })

def clean_markdown_inline(text):
    """Converts basic markdown inline bold and code tags to XML tags for ReportLab Paragraph."""
    # Convert <br> or <br/> variants to temporary token
    text = re.sub(r'<br\s*/?>', '___BR___', text, flags=re.IGNORECASE)
    
    # Convert `code` to placeholder
    code_matches = []
    def code_repl(m):
        code_matches.append(m.group(1))
        return f"___CODE_{len(code_matches)-1}___"
    text = re.sub(r'`(.+?)`', code_repl, text)
    
    # Convert **bold** or __bold__ to placeholder
    bold_matches = []
    def bold_repl(m):
        bold_matches.append(m.group(1))
        return f"___BOLD_{len(bold_matches)-1}___"
    text = re.sub(r'\*\*(.+?)\*\*', bold_repl, text)
    text = re.sub(r'__(.+?)__', bold_repl, text)

    # Escape XML special characters
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

    # Restore bold
    for i, b in enumerate(bold_matches):
        b_escaped = b.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        text = text.replace(f"___BOLD_{i}___", f"<b>{b_escaped}</b>")

    # Restore code
    for i, c in enumerate(code_matches):
        c_escaped = c.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        text = text.replace(f"___CODE_{i}___", f'<font name="Courier" color="#0369a1">{c_escaped}</font>')

    # Restore BR as self-closing XML tag
    text = text.replace('___BR___', '<br/>')
    return text

def build_pdf_from_data(data, output_path):
    """Builds a formatted PDF report from structured dictionary data."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=landscape(letter),
        leftMargin=36,
        rightMargin=36,
        topMargin=42,
        bottomMargin=42
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12
    )
    
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=10,
        spaceAfter=6
    )
    
    th_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#ffffff')
    )
    
    cell_bold = ParagraphStyle(
        'CellBold',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0f172a')
    )
    
    cell_normal = ParagraphStyle(
        'CellNormal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10.5,
        textColor=colors.HexColor('#334155')
    )

    story = []

    doc_title = clean_markdown_inline(data.get("title", "Release Notes: New Capabilities & Enhancements"))
    doc_subtitle = clean_markdown_inline(data.get("subtitle", "Categorized breakdown of features, simplified explanations, examples, and use cases."))
    
    story.append(Paragraph(doc_title, title_style))
    story.append(Paragraph(doc_subtitle, subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceBefore=0, spaceAfter=10))

    # Column widths (Total width = 720pt)
    col_widths = [120, 220, 170, 210]

    for section in data.get("sections", []):
        section_title = clean_markdown_inline(section.get("title", "Section"))
        items = section.get("items", [])
        if not items:
            continue
        
        table_data = [
            [
                Paragraph("Capability / Enhancement", th_style),
                Paragraph("Simple Explanation", th_style),
                Paragraph("Example", th_style),
                Paragraph("Real-World Use Case", th_style)
            ]
        ]

        for item in items:
            table_data.append([
                Paragraph(clean_markdown_inline(item.get("capability", "")), cell_bold),
                Paragraph(clean_markdown_inline(item.get("explanation", "")), cell_normal),
                Paragraph(clean_markdown_inline(item.get("example", "")), cell_normal),
                Paragraph(clean_markdown_inline(item.get("use_case", "")), cell_normal)
            ])

        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#ffffff'), colors.HexColor('#f8fafc')]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('LINEBELOW', (0, 0), (-1, 0), 1, colors.HexColor('#0f172a')),
        ]))

        story.append(KeepTogether([
            Paragraph(section_title, section_heading),
            t,
            Spacer(1, 10)
        ]))

    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"Successfully generated PDF: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate PDF from structured release notes Markdown or JSON file.")
    parser.add_argument("--input", required=True, help="Path to input Markdown (.md) or JSON (.json) file.")
    parser.add_argument("--output", required=True, help="Path to output PDF.")
    parser.add_argument("--title", help="Optional override for document title.")
    parser.add_argument("--subtitle", help="Optional override for document subtitle.")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"Error: Input file {args.input} not found.", file=sys.stderr)
        sys.exit(1)

    if args.input.endswith(".json"):
        with open(args.input, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read()
        data = parse_markdown_tables(content)

    if args.title:
        data["title"] = args.title
    if args.subtitle:
        data["subtitle"] = args.subtitle

    build_pdf_from_data(data, args.output)

if __name__ == "__main__":
    main()
